### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by U1F984** [erthalion/erthalion.github.io#1]
Hi,

I am really enjoying your blog :). I've found your RSS feed after looking at this repo, but I think a link from the blog would be helpful to others. 

BR
Leo

**Comment by erthalion** [comment]
> I am really enjoying your blog :). I've found your RSS feed after looking at this repo, but I think a link from the blog would be helpful to others.

Thanks :) Haven't thought it could be useful for someone, will add it soon.

**Comment by erthalion** [comment]
Added in feea2b8
